# Generated by Django 5.0.3 on 2024-03-16 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_alter_clothingitem_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Status Name')),
            ],
            options={
                'verbose_name_plural': 'Order Status',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Date of Create')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Date of Update')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderstatus', verbose_name='Order Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'User Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('add_service', models.ManyToManyField(to='store.additionalservice', verbose_name='Additional Service')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.clothingitem', verbose_name='Clothes')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.fabric', verbose_name='Fabric')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.size', verbose_name='Size')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='order.userorder', verbose_name='Order ID')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
